// pi-pdf.ts — Renders the Pro-Forma Invoice PDF for a published PI.
//
// Odoo's own native report (`sale.report_saleorder_pro_forma`) cannot be
// generated by this portal: calling ir.actions.report._render_qweb_pdf over
// XML-RPC is refused by Odoo itself ("Private methods ... cannot be called
// remotely" — verified live), and the web /report/pdf/ endpoint needs an
// interactive session login that this portal's API service account cannot
// obtain ("Access Denied" — verified live, most likely because it's an
// RPC-only technical account by design). So this renders a look-alike PDF
// from data already read via XML-RPC — company/address/GST, product lines,
// taxes, totals, and the same bank-details/terms boilerplate InBody's real
// quotations already carry (copied verbatim from live historical orders).
// Never Odoo's byte-identical native template — see
// CULTFIT_PORTAL_MASTER_CONTEXT.md §Phase 2 for the full rationale.

import 'server-only';
import PDFDocument from 'pdfkit';

export interface PILineItem {
  code: string;
  description: string;
  quantity: number;
  unitPrice: number;
  taxLabel: string;
  taxAmount: number;
  lineTotal: number;
}

export interface PIPdfData {
  quotationNumber: string;
  version: number;
  requestReference: string;
  cultfitCompanyName: string;
  deliveryAddress: string;
  cocoFofo: 'COCO' | 'FOFO';
  preferredDeliveryDate: string | null;
  salespersonName: string;
  // Only verified for the two products with a confirmed historical bundle
  // rule (InBody 260/260S -> 5 years, InBody 120 -> 1 year) — null for any
  // other main product, which prints a generic phrase instead of a guessed
  // number. See BUNDLE_MAP / WARRANTY_YEARS_MAP in odoo-server.ts.
  warrantyYears: number | null;
  lineItems: PILineItem[];
  untaxedAmount: number;
  taxAmount: number;
  totalAmount: number;
  validityDate: string;
  publishedDate: string;
}

// "Rs." not "₹" — pdfkit's core Helvetica font only supports WinAnsiEncoding,
// which has no Indian Rupee glyph (U+20B9); it silently renders as a stray
// superscript-1 instead. Confirmed visually against a real generated PDF.
function fmtInr(n: number): string {
  return 'Rs. ' + n.toLocaleString('en-IN', { maximumFractionDigits: 2 });
}

function fmtDate(d: string): string {
  const dt = new Date(d);
  if (Number.isNaN(dt.getTime())) return d;
  return dt.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

export async function generatePIPdf(data: PIPdfData): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', c => chunks.push(c as Buffer));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // ── Header ──────────────────────────────────────────────────────────
    doc.fontSize(14).font('Helvetica-Bold').text('InBody India Private Limited', { continued: false });
    doc.fontSize(9).font('Helvetica')
      .text('B Wing, Second floor, Art Guild House, Pheonix Market city, Kurla west, Mumbai, Maharashtra 400070, India')
      .text('GSTIN: 27AAECI1883N1Z2');

    doc.moveDown(0.5);
    doc.fontSize(16).font('Helvetica-Bold').text('PRO-FORMA INVOICE', { align: 'right' });
    doc.fontSize(9).font('Helvetica').text(`${data.quotationNumber}  ·  Version ${data.version}`, { align: 'right' });
    doc.text(`Published: ${fmtDate(data.publishedDate)}`, { align: 'right' });
    doc.text(`Valid until: ${fmtDate(data.validityDate)}`, { align: 'right' });

    doc.moveDown(1);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown(0.8);

    // ── Bill To / Reference ─────────────────────────────────────────────
    const colTop = doc.y;
    doc.fontSize(9).font('Helvetica-Bold').text('Bill To / Ship To', 50, colTop);
    doc.font('Helvetica').text(data.cultfitCompanyName, 50, doc.y + 2, { width: 240 });
    doc.text(data.deliveryAddress, { width: 240 });

    doc.font('Helvetica-Bold').text('Reference', 320, colTop);
    doc.font('Helvetica').text(`Request: ${data.requestReference}`, 320, colTop + 14, { width: 220 });
    doc.text(`Type: ${data.cocoFofo}`, 320, undefined, { width: 220 });
    if (data.preferredDeliveryDate) doc.text(`Preferred delivery: ${fmtDate(data.preferredDeliveryDate)}`, 320, undefined, { width: 220 });
    doc.text(`Salesperson: ${data.salespersonName}`, 320, undefined, { width: 220 });

    doc.moveDown(2);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown(0.8);

    // ── Line items table ─────────────────────────────────────────────────
    const tableTop = doc.y;
    const cols = { desc: 50, qty: 300, price: 350, tax: 420, total: 480 };
    doc.fontSize(9).font('Helvetica-Bold');
    doc.text('Description', cols.desc, tableTop, { width: 245 });
    doc.text('Qty', cols.qty, tableTop, { width: 45, align: 'right' });
    doc.text('Unit Price', cols.price, tableTop, { width: 65, align: 'right' });
    doc.text('Tax', cols.tax, tableTop, { width: 55, align: 'right' });
    doc.text('Amount', cols.total, tableTop, { width: 65, align: 'right' });
    doc.moveDown(0.4);
    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#000000').stroke();
    doc.moveDown(0.4);

    doc.font('Helvetica');
    for (const line of data.lineItems) {
      const rowTop = doc.y;
      doc.text(`[${line.code}] ${line.description}`, cols.desc, rowTop, { width: 245 });
      doc.text(String(line.quantity), cols.qty, rowTop, { width: 45, align: 'right' });
      doc.text(fmtInr(line.unitPrice), cols.price, rowTop, { width: 65, align: 'right' });
      doc.text(line.taxLabel, cols.tax, rowTop, { width: 55, align: 'right' });
      doc.text(fmtInr(line.lineTotal), cols.total, rowTop, { width: 65, align: 'right' });
      doc.moveDown(0.6);
    }

    doc.moveTo(50, doc.y).lineTo(545, doc.y).strokeColor('#cccccc').stroke();
    doc.moveDown(0.6);

    // ── Totals ──────────────────────────────────────────────────────────
    const totalsX = 380;
    doc.font('Helvetica').text('Untaxed Amount', totalsX, doc.y, { width: 100, align: 'left' });
    doc.text(fmtInr(data.untaxedAmount), cols.total, doc.y - doc.currentLineHeight(), { width: 65, align: 'right' });
    doc.text('Tax', totalsX, doc.y, { width: 100, align: 'left' });
    doc.text(fmtInr(data.taxAmount), cols.total, doc.y - doc.currentLineHeight(), { width: 65, align: 'right' });
    doc.font('Helvetica-Bold').fontSize(11);
    doc.text('Total', totalsX, doc.y, { width: 100, align: 'left' });
    doc.text(fmtInr(data.totalAmount), cols.total, doc.y - doc.currentLineHeight(), { width: 65, align: 'right' });

    doc.moveDown(1.5);
    const FULL_WIDTH = 495; // 545 - 50 margins

    // ── Terms & bank details — same boilerplate InBody's real quotations
    // carry today (copied verbatim from live historical CultFit orders,
    // warranty years parameterized per product family). Explicit x/width on
    // every call below — without it, pdfkit inherits the narrow ~65pt
    // column width left over from the totals block above, wrapping this
    // entire section into an unreadable single column (confirmed visually
    // against a real generated PDF).
    doc.fontSize(9).font('Helvetica-Bold').text('Terms & Conditions', 50, doc.y, { width: FULL_WIDTH });
    const warrantyLine = data.warrantyYears != null
      ? `3. WARRANTY: ${data.warrantyYears} year${data.warrantyYears === 1 ? '' : 's'} from the date of delivery/installation.\n`
      : '3. WARRANTY: As per InBody\'s standard warranty policy for this product.\n';
    doc.font('Helvetica').fontSize(8).text(
      '1. PRICES: The prices are firm, inclusive of air freight, insurance charges, customs duty, custom clearance '
      + 'expenses, secondary freight & insurance charges, from Mumbai to any major port in India.\n'
      + '2. PAYMENT TERMS: 100% payment along with the order.\n'
      + warrantyLine
      + '4. DELIVERY PERIOD: Ex-stock or four weeks from the date of receipt of the confirmed order.\n'
      + `5. VALIDITY: The prices will remain valid till ${fmtDate(data.validityDate)}.`,
      50, doc.y, { width: FULL_WIDTH },
    );

    doc.moveDown(0.8);
    doc.font('Helvetica-Bold').fontSize(8).text('InBody India Bank Details (for bank transfer)', 50, doc.y, { width: FULL_WIDTH });
    doc.font('Helvetica').text(
      'Name: INBODY INDIA PVT. LTD.\n'
      + 'Account No.: 196205000495\n'
      + 'Bank Name: ICICI Bank Limited\n'
      + 'Branch: Kurla (West)\n'
      + 'IFSC: ICIC0001962\n'
      + 'Account Type: Current Account\n'
      + 'Currency: Indian Rupees',
      50, doc.y, { width: FULL_WIDTH },
    );

    doc.end();
  });
}
